# Generated by Django 3.2.5 on 2021-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=30)),
                ('country_represnt', models.CharField(default='', max_length=20)),
                ('country_noTeams', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
                ('game_name', models.CharField(default='', max_length=40)),
                ('game_noParti', models.IntegerField(default=0)),
            ],
        ),
    ]
