# Generated by Django 3.2.5 on 2021-07-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrygame',
            name='country_flag',
            field=models.ImageField(default='', upload_to='country/images'),
        ),
    ]
